services:
  app:
    build:
      context: .
      dockerfile: apps/app/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - ENVIRONMENT=PRODUCTION
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ENVIRONMENT=PRODUCTION
